Climb commands
SummitRobotics/FRC2022 pull request #33
Opened 2022-02-19 02:13 UTC by josiahcrossman

Made auto climb system, added power draw methods for various subsystems.

2022-02-19 05:29 UTC, Xmde requested changes
Looks good but I feel like you are missing the automation in the ClimbAutomation command. You also have the Shooter automation code in this branch and that should get cleaned up and fixed.

2022-02-19 05:29 UTC, Xmde commented on src/main/java/frc/robot/commands/climb/ClimbAutomation.java
> +
I feel like you are missing stuff here. Are you still planning to implement this or did you forget to commit/push your changes?

2022-02-19 05:29 UTC, Xmde commented on src/main/java/frc/robot/commands/shooter/SemiAutoShooterAssembly.java
> +package frc.robot.commands.shooter;
See the previous comment.

2022-02-19 05:29 UTC, Xmde commented on src/main/java/frc/robot/commands/shooter/FullAutoShooterAssembly.java
> +package frc.robot.commands.shooter;
I feel like you accidentally merged in the Shooter Assembly branch or made this branch from that one. Clean up the branch and remove the files associated with the shooter assembly.

2022-02-19 05:29 UTC, Xmde commented on src/main/java/frc/robot/commands/climb/ClimbAutomation.java
> +    pivotPistLeft = climbStates.UNKNOWN;
These states are known to be retracted at the beginning of the match.

2022-02-19 07:20 UTC, django-wardlow-1819 requested changes

2022-02-19 07:20 UTC, django-wardlow-1819 commented on src/main/java/frc/robot/subsystems/Climb.java
> +    private final Solenoid pivotLeft =
pivot left and right are on the same solenoid

2022-02-19 07:20 UTC, django-wardlow-1819 commented on src/main/java/frc/robot/commands/climb/ClimbMO.java
> +    OIButton leftPivotButton;
left and right pivot are the same, they can not be controled independently

2022-02-19 07:20 UTC, django-wardlow-1819 commented on src/main/java/frc/robot/commands/climb/ClimbAutomation.java
> +    climbStates pivotPistLeft;
left and right pivots are on the same solinoid

2022-03-17 22:47 UTC, Xmde commented
Is this still a pull request you want me to take a look at or is all of this code already in the testing branch?

2022-03-19 04:50 UTC, closed without merging

2022-03-19 04:51 UTC, Xmde commented
Closing PR because changes already in testing branch.